### ISSUE TITLE
Diseño de la pantalla "Home"

### ISSUE THREAD

**Issue by MarcGM10** [TheRabbot17/Bet-Tracking#1]
Diseño real de la vista que tendrá cualquier persona al acceder a la aplicación siguiendo el esquema y términos acordados.

**Comment by AlejandroSanchezO** [comment]
Hemos encontrado un par de herramientas de trabajo para el diseño de la pagina inicial y estamos probando y familiarizándonos con ésta. Falta detallar las funcionalidades y concretar los colores y distribución de la página.
